// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import QuitSmokingTimerController from "./quit_smoking_timer_controller"
application.register("quit-smoking-timer", QuitSmokingTimerController)

import CigaretteFormController from "./cigarette_form_controller"
application.register("cigarette-form", CigaretteFormController)