# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
cigarette_brands = [
  { name: "メビウス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・１００'s・BOX", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・ライト", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・ライト・BOX", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・ライト・１００'s・ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・スーパーライト", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・スーパーライトボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・スーパーライト・１００'ｓ・ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・エクストラライト", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・エクストラライト・ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・エクストラライト・１００'ｓボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・ワン", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・ワン・ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・ワン・１００'ｓ・ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウスイーシリーズ・10", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "メビウスイーシリーズ・6", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "メビウスイーシリーズ・ワン100sボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "メビウスイーシリーズ・メンソール・5", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "メビウスイーシリーズ・メンソールワン・100sボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "メビウスｺﾞｰﾙﾄﾞ６ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "メビウス・ゴールド・ワン・１００'ｓボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "セブンスター", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "セブンスター・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "セブンスター・10・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "セブンスター・７・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "セブンスター・4", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "ウィンストン・キャスターホワイト5", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ウィンストン・キャスターホワイトボックス5", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ウィンストン・キャスターホワイト3", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ウィンストン・キャスターホワイト3ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ウィンストン・キャスターホワイトワン・ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ウィンストン・キャスターホワイトワン・１００'ｓ・ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ホープ", price_per_pack: 300, quantity_per_pack: 10 },
  { name: "ホープ・ライト", price_per_pack: 300, quantity_per_pack: 10 },
  { name: "ホープ・スーパーライト", price_per_pack: 300, quantity_per_pack: 10 },
  { name: "ホープ・メンソール", price_per_pack: 300, quantity_per_pack: 10 },
  { name: "ピース", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "ピース・ライト・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "ピース・スーパーライト・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "ピース・アロマ・ロイヤル・100sボックス", price_per_pack: 640, quantity_per_pack: 20 },
  { name: "ピース・アロマ・クラウン・100sボックス", price_per_pack: 640, quantity_per_pack: 20 },
  { name: "ピース・アロマ・インフィニティ", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "ナチュラル・アメリカン・スピリットターコイズ", price_per_pack: 420, quantity_per_pack: 14 },
  { name: "ナチュラル・アメリカン・スピリット・ゴールド", price_per_pack: 420, quantity_per_pack: 14 },
  { name: "ナチュラル・アメリカン・スピリット・オーガニックリーフONE", price_per_pack: 420, quantity_per_pack: 14 },
  { name: "ナチュラル・アメリカン・スピリット・オーガニックミントライト", price_per_pack: 420, quantity_per_pack: 14 },
  { name: "ナチュラル・アメリカン・スピリットオーガニックミントウルトラライト", price_per_pack: 420, quantity_per_pack: 14 },
  { name: "ナチュラル・アメリカン・スピリット・オーガニックミントONE", price_per_pack: 420, quantity_per_pack: 14 },
  { name: "ナチュラル・アメリカン・スピリット・ライト", price_per_pack: 420, quantity_per_pack: 14 },
  { name: "キャメル・クラフト14・ボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "キャメル・クラフト10・ボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "キャメル・クラフト3・ボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "キャメル・クラフト12・ボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "キャメル・クラフト6・ボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "キャメル・クラフト1・100sボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "キャメル・クラフトメンソール・5・ボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "キャメル・クラフトメンソール・1・100sボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "ハイライト", price_per_pack: 520, quantity_per_pack: 20 },
  { name: "ハイライト・メンソール", price_per_pack: 520, quantity_per_pack: 20 },
  { name: "ピアニッシモ・アリア・メンソール", price_per_pack: 570, quantity_per_pack: 20 },
  { name: "ピアニッシモ・ペティル・メンソール", price_per_pack: 570, quantity_per_pack: 20 },
  { name: "ピアニッシモ・アイシーン・メンソール5", price_per_pack: 570, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・ＦＫ", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・エキスパートカット・6", price_per_pack: 450, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・エキスパートカット・10", price_per_pack: 450, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・エキスパートカット・14", price_per_pack: 450, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・ブラックシリーズ・5", price_per_pack: 450, quantity_per_pack: 20 },
  { name: "ラッキー・ストライクブラックシリーズメンソール・8", price_per_pack: 450, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・ブラックシリーズ・スーパーソニック・5", price_per_pack: 450, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・ブラックシリーズ・チルベリー・5", price_per_pack: 450, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・ブラックシリーズ・チルベリー・8", price_per_pack: 450, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "ラッキー・ストライク・ライト・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・アイス・ブラスト・メガ・1・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・アイス・ブラスト・メガ・5・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・アイス・ブラスト・メガ・8・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・ゴールドオリジナル・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・ゴールドオリジナル・100　ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・ダブル・バースト・パープル・5・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・ダブル・バースト・5・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・ブラック・メンソール・8ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・ミディアム・ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・メンソール・4ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・メンソール・8ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "マールボロ・メンソール・8・100ボックス", price_per_pack: 600, quantity_per_pack: 20 },
  { name: "ラーク・ＫＳボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・100ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・アイス・ミント5・100ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・マイルド・メンソール・ＫＳボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・ウルトラ・メンソール・ＫＳボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・ウルトラ・メンソール・100ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・ウルトラ・1㎎・ＫＳボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・ウルトラ・1㎎・100ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・エクストラ・3㎎・ＫＳボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・エクストラ・3㎎・100ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・クラシック・マイルド", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・スーパー・メンソール・ＫＳボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラークスーパー・5㎎ks・ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラークスーパー・5㎎100ｓボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・ハイブリッド・KSボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・ハイブリット・ワン100ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・マイルドＫＳボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ラーク・マイルド・100ボックス", price_per_pack: 540, quantity_per_pack: 20 },
  { name: "ケント・１・ＫＳボックス", price_per_pack: 520, quantity_per_pack: 20 },
  { name: "ケント・１・１００ボックス", price_per_pack: 520, quantity_per_pack: 20 },
  { name: "ケント・３・１００ボックス", price_per_pack: 520, quantity_per_pack: 20 },
  { name: "ケント・６・１００ボックス", price_per_pack: 520, quantity_per_pack: 20 },
  { name: "ケント・アイブースト・１・１００ボックス", price_per_pack: 520, quantity_per_pack: 20 },
  { name: "ケント・エス・シリーズ・スパーク・１・100・ボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "ケント・エス・シリーズ・スパーク・5・100・ボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "ケント・エス・シリーズ・スパーク・ミント1・100・ボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "ケント・エス・シリーズ・スパーク・ミント5・100・ボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "ケント・エス・シリーズ・スパーク・メロー・1・100・ボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "ケント・エス・シリーズ・メンソール・１・100・ボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "ケント・エス・シリーズ・１・100・ボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "ケント・エス・シリーズ・3・100・ボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "ケント・エス・シリーズ・6・100・ボックス", price_per_pack: 500, quantity_per_pack: 20 },
  { name: "パーラメント・ＫＳボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "パーラメント・１００ボックス", price_per_pack: 620, quantity_per_pack: 20 },
  { name: "パーラメント・エクストラ・ライト・１００ボックス", price_per_pack: 620, quantity_per_pack: 20 },
  { name: "パーラメント・ライト・ＫＳボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "パーラメント・ライト・１００ボックス", price_per_pack: 620, quantity_per_pack: 20 },
  { name: "パーラメント・ワン・ＫＳボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "パーラメント・ワン・１００ボックス", price_per_pack: 620, quantity_per_pack: 20 },
  { name: "クール・ＦＫ・ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "クール・ブーストフレッシュ5・ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "クール・ブースト・フレッシュ8ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "クール・マイルド・ＦＫボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "クール・ライト・ボックス", price_per_pack: 580, quantity_per_pack: 20 },
  { name: "バージニア・エス・ソフィア1", price_per_pack: 570, quantity_per_pack: 20 },
  { name: "バージニア・エス・ソフィア6", price_per_pack: 570, quantity_per_pack: 20 },
  { name: "バージニア・エス・デュオ・メンソール１０'ｓ", price_per_pack: 290, quantity_per_pack: 10 },
  { name: "フィリップモリス・6・ksボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "フィリップモリス・10・ksボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "フィリップモリス・14・ksボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "フィリップモリス・メンソール5・ksボックス", price_per_pack: 430, quantity_per_pack: 20 },
  { name: "フィリップモリス・メンソール8・ksボックス", price_per_pack: 430, quantity_per_pack: 20 },
]

begin
  ActiveRecord::Base.transaction do
    CigaretteBrand.delete_all
    CigaretteBrand.insert_all!(cigarette_brands)
  end
  puts "#{CigaretteBrand.count} cigarette brands have been seeded."
rescue => e
  puts "An error occurred while seeding the database: #{e.message}"
end